### ISSUE TITLE
Issue with gitignore

### ISSUE THREAD

**Issue by PatrickPiazza** [Bloomfield-SP22-CAT327/Assignment10-PatrickPiazza#1]
I committed with a gitignore using the Unity template, but for some reason the builds and library folders still appeared in the repo.

**Comment by ProfPollati** [comment]
You committed the updated `.gitignore` after you already committed files in "Builds/" and "Library/".

If you're using GitHub Desktop, you will need to delete the "Builds/" and "Library/" and commit that, which should now delete those files from the repo. In order to delete all the "Library/" files, you'll need to quit Unity or close the project first.

If you are comfortable with command prompt, and you had git installed there are a few steps you could do to have [git remove gitignored files](https://stackoverflow.com/questions/1274057/how-can-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitign)
